### ISSUE TITLE
About the setUpFitting function

### ISSUE THREAD

**Issue by jingzbu** [vgupta1/InverseVIs#1]
1) In https://github.com/vgupta1/InverseVIs/blob/master/Traffic/fitTraffic.jl#L17, the arguments `odpairs`, `nodes` never appear later within the `setUpFitting()` function, but in https://github.com/vgupta1/InverseVIs/blob/master/Traffic/trafficCval.jl#L116, these two arguments are still assigned values; why?

2) In https://github.com/vgupta1/InverseVIs/blob/master/Traffic/fitTraffic.jl#L26, the kernel matrix `K` is specified independent of the data points. Why?

**Comment by vgupta1** [comment]
Re:
1) This is just a superfluous argument.  It's possible to drop it.
2) The key mathematical observation in the RKHS is finite dimensional (of dim deg + 1).  If we express the function f directly in terms of the true Graham matrix of the data points, K will have rank at most deg +1, and this causes severe numerical difficulties.  A better choice is to do a change of variables and re-express everything in terms of the standard basis for the polynomials.  This also is a massive variable reduction in the optimization problem at the expense of some pre-processing.
